os:
  - linux
language: node_js
node_js:
  - "node"

before_script:
  - npm i -g mocha nyc typescript
  - npm i

jobs:
  include:
    - stage: "Test"
      if: NOT tag =~ ^v*
      script: npm run coverage

    - stage: "Deploy"
      deploy:
        provider: npm
        node: node
        email: $NPM_EMAIL_ADDR
        api_key: $NPM_API_KEY
        edge: true
        skip_cleanup: true
        on:
          tags: true
          branch: master

notifications:
  email:
    recipients:
      - hello@lsantos.dev
    on_success: change
    on_failure: always
